## Numpy练习

### 1. 创建一个长度为10全为0的向量，然后让第5个元素等于1。

In [1]:
import numpy as np
data=np.zeros(10)
data[4]=1
print(data)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. 生成一个4X5和一个5X4的随机数矩阵，并计算它们的乘积。

In [16]:
import numpy as np
a=np.random.rand(4,5)
b=np.random.rand(5,4)
print(a)
print(b)
print(a@b)

[[0.92651122 0.66787345 0.28588879 0.23928799 0.86810885]
 [0.27485795 0.96368334 0.7336464  0.72749235 0.45567131]
 [0.20186342 0.55439855 0.80543581 0.77693653 0.73036096]
 [0.51694516 0.91525691 0.7003846  0.96081521 0.37050722]]
[[0.94568022 0.24485025 0.20310939 0.11809573]
 [0.67608002 0.58879405 0.92256802 0.52811811]
 [0.55457912 0.52727975 0.77590871 0.2100623 ]
 [0.02584484 0.14745148 0.08388034 0.33841477]
 [0.83840813 0.98064443 0.38759287 0.58108203]]
[[2.22028106 1.65742926 1.38270978 1.10760858]
 [1.7191602  1.5756683  1.75176954 1.20648619]
 [1.64481428 1.63132772 1.52566779 1.17314525]
 [1.83153878 1.53978006 1.71701714 1.23198632]]


### 3. 函数 f 定义如下，其中x是任意实数: 𝑓(𝑥)=(sin⁡(𝑥+1)/𝑒^𝑥 )(𝑥+1)/2，生成一个包含5个元素的一维数组a，计算b = f(a)。

In [6]:
import numpy as np
def fx(n:np.ndarray) -> np.ndarray:
    """fx function."""
    return (np.sin(n+1)/np.exp(n))*(n+1)/2
a=np.random.rand(5)
b=fx(a)
print(a)
print(b)





[0.89896867 0.79116845 0.39948091 0.53191544 0.80199968]
[0.36580725 0.3961634  0.46242378 0.4496437  0.3932857 ]
0.33451182923926226


### 4. 随机生成一个5行10列的矩阵，然后每行元素减去该行的平均值

In [29]:
import numpy as np
a=np.random.rand(5,10)
b=np.mean(a,axis=1)
print(a)
print(b)
c=a-b.reshape(-1,1)
print(c)



[[0.73826719 0.03275902 0.67080486 0.09487017 0.29783417 0.52945458
  0.67482165 0.90161854 0.84040298 0.71683807]
 [0.42008032 0.62118366 0.0018611  0.3561263  0.35179593 0.03756861
  0.90621531 0.0232989  0.66042298 0.50864405]
 [0.67288514 0.78555931 0.27385594 0.89115522 0.55319408 0.9416889
  0.26432715 0.06232011 0.63420346 0.48972311]
 [0.86581389 0.87648447 0.88209582 0.21992399 0.3851975  0.47543529
  0.04567489 0.80514231 0.01115726 0.60116136]
 [0.96278458 0.76744632 0.55565933 0.61442191 0.3162239  0.30590465
  0.28272388 0.64754147 0.84257063 0.29158777]]
[0.54976712 0.38871972 0.55689124 0.51680868 0.55868644]
[[ 0.18850007 -0.51700811  0.12103774 -0.45489695 -0.25193295 -0.02031255
   0.12505453  0.35185141  0.29063585  0.16707095]
 [ 0.03136061  0.23246395 -0.38685862 -0.03259342 -0.03692378 -0.35115111
   0.51749559 -0.36542082  0.27170327  0.11992434]
 [ 0.11599389  0.22866807 -0.28303531  0.33426398 -0.00369716  0.38479766
  -0.29256409 -0.49457114  0.07731222 -0.067